### ISSUE TITLE
A car racing game with python

### ISSUE THREAD

**Issue by CodeYard01** [Shahrayar123/Python-Projects#153]
A car racing game which have basic control features , scores feature with many hurdles and also made up from pure python .
game development libraries of python can be used for this project.

**Comment by CodeYard01** [comment]
please assign this task to me i have a car game for this issue . please give this to me.

**Comment by imumer68** [comment]
**I've finished the task carefully. Please take a look at the pull request.**

**Comment by Ankit-Mazumdar** [comment]
Please review and merge my pull request.

**Comment by Sagarachdeva911** [comment]
Hi, we'd like to work on this issue as a group.
@bhavyajain123 ,@Praptijain10 and me
