### ISSUE TITLE
Alarm Clock with Tkinter(GUI)

### ISSUE THREAD

**Issue by TimTemi** [Shahrayar123/Python-Projects#39]
Creating an alarm clock with python tkinter and other python libraries.

**Comment by TimTemi** [comment]
@Shahrayar123 , assign me this task. And if my PR gets merged and will be valid by hacktoberfest, do let me know. Thanks

**Comment by Shahrayar123** [comment]
Hi @TimTemi,
You can create a PR for this, I will merge it after review.

**Comment by TimTemi** [comment]
@Shahrayar123 , alright then. Will do.

**Comment by adityanain29** [comment]
Hey @TimTemi  if it's not done kindly assign it to me.
I am a newbie but yeah I will be able to do it
Thanks

**Comment by TimTemi** [comment]
Hello @adityanain29. I've been quite carried away. But its fine. You can take over the task.

**Comment by adityanain29** [comment]
Thanks a lot @TimTemi 👍

**Comment by impeccable16** [comment]
Hi @TimTemi 
could you please elaborate it more.

**Comment by iligeoili** [comment]
If TimTemi this issue is still open i would like to work on it

**Comment by TimTemi** [comment]
@Yash-sudo-web @iligeoili you both can work on it.

**Comment by Anupamsh30** [comment]
@TimTemi Can you assign me this issue?
Thanks

**Comment by TimTemi** [comment]
@Anupamsh30  Sure you can go ahead.

**Comment by champati-v** [comment]
Hii! @TimTemi 
As I obeserved, there is no progress on this issue yet, can you assign me this task, I can complete this within a day. 

Thanks and regards, 
Vibekananda champati

**Comment by filza2112** [comment]
HI, please assign this issue to me. I have worked with python and Tkinter before. 
please check my PR #76

**Comment by TimTemi** [comment]
@aaryansr26 @Anupamsh30 @Anupamsh30 @filza2112 You all can work on the alarm clock, if you are still interested.

**Comment by filza2112** [comment]
@TimTemi Please check my PR #76

**Comment by filza2112** [comment]
@Shahrayar123 please check my PR #76

**Comment by tromkk** [comment]
Hi @TimTemi, since #76 got merged is this issue now closed?

**Comment by TimTemi** [comment]
@tromkk  YOU CAN RAISE AN ISSUE.
