### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by varadtote** [Shahrayar123/Python-Projects#44]
Creating a Password Generator with Python random module

**Comment by anshuman0123** [comment]
assign

**Comment by Manish254252** [comment]
anyone working on this issue if not i would like solve it .

**Comment by iligeoili** [comment]
i would like to work on this issue if its possible

**Comment by Lokesh396** [comment]
It's still open anyone working on it or else i will work on it, thanks.

**Comment by 30adi** [comment]
is anyone still working on this?

**Comment by Yash-sudo-web** [comment]
Opened Pull request #58 regarding this

**Comment by Anupamsh30** [comment]
@varadtote  If this is still open can you assign this to me?

**Comment by AIVAN22** [comment]
Can i have it as well :)
