### ISSUE TITLE
New project

### ISSUE THREAD

**Issue by ThaysonScript** [Shahrayar123/Python-Projects#50]
Simple Calculator beginner project

**Comment by Lokesh396** [comment]
Describe more about the project, if the project is about building a calculator using tkinter then assign it to me, I have built some calculators using tkinter

**Comment by ThaysonScript** [comment]
It can be with tkinter even. I thought of a simple application, but we can use this wonderful module

**Comment by ThaysonScript** [comment]
> Describe more about the project, if the project is about building a calculator using tkinter then assign it to me, I have built some calculators using tkinter.

Use github flow for this project!

**Comment by Yash-sudo-web** [comment]
is anyone working on this? can you assign this to me?
