### ISSUE TITLE
Riddle

### ISSUE THREAD

**Issue by SinanTokmak** [Shahrayar123/Python-Projects#56]
Creating a Riddle Generator with Python random module

**Comment by SinanTokmak** [comment]
@Shahrayar123 @Rohit-554 @Sj0605-DataSci @harshbaid-13 @kasyap1234 @arunkarthicknm @Scaratek @redeagle17 @marsian83  @Code-xed  @Saurav017 

can you give me a assign?

**Comment by kush-og** [comment]
Is this issue still open or else you can assign this to me?

**Comment by harisdev-netizen** [comment]
Can you assign this to me?

**Comment by SinanTokmak** [comment]
@Shahrayar123 it is ready https://github.com/Shahrayar123/Python-Projects/pull/67

**Comment by harisdev-netizen** [comment]
> @Shahrayar123 it is ready #67

I already created a PR last night 😀

**Comment by SinanTokmak** [comment]
> > @Shahrayar123 it is ready #67
> 
> I already created a PR last night 😀

But I wanted it assigned to me. I just waited for it to be assigned. Maybe 3 files can be combined in one place. Not sure how to decide.

**Comment by SinanTokmak** [comment]
I've waited a month to write this.

**Comment by harunfr** [comment]
Can you assign this to me? This riddle idea is just exceptional.

**Comment by harisdev-netizen** [comment]
> Can you assign this to me? This riddle idea is just exceptional.

This issue has already been resolved. I an @SinanTokmak already worked on this. 😀😁

**Comment by SinanTokmak** [comment]
This issue has been resolved. Thank you.
