### ISSUE TITLE
Add README.md file in this repo

### ISSUE THREAD

**Issue by Ayush0431** [Shahrayar123/Python-Projects#6]

**Comment by vishwas1636** [comment]
Hi I will work on creating readme file so for that I need to know about this project.

**Comment by Ayush0431** [comment]
> Hi I will work on creating readme file so for that I need to know about this project.

this repo is basically about python projects , so you can add a project and add a readme about definition of that project moreover you can add templates about your project😊.

**Comment by kasyap1234** [comment]
I am beginner , I would like to contribute by creating a readme file for this project .
